from django import forms#314e6c
from .models import *
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class blogg(forms.ModelForm):
	comment=forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Comment here'}),
							max_length=500,required=True)
	image=forms.FileField(required=False) 

	class Meta:
		model=blog1
		fields=['comment','image']
# custom validation on username
class regform(forms.ModelForm):
	first_name=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'First name'}),
								max_length=30,required=True)
	last_name=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Last name'}),
							max_length=30,required=False)
	username=forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Enter Email address'}),
									max_length=50,
									required=True)
	password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Choose a password'}),
									max_length=50,
									required=True)

	confirm_password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Confirm password'}),
									max_length=50,
									required=True)


	def clean_username(self):
		username=self.cleaned_data['username']
		try:
			match=User.objects.get(username=username)
		except:
			return self.cleaned_data['username']
		raise forms.ValidationError('Email already Register')

	class Meta:
		model=User
		fields=['first_name','last_name','username','password','confirm_password',]


class profile1(forms.ModelForm):
	dob=forms.DateField(widget=forms.DateInput())
	profile_pic=forms.FileField(required=False)
	mobile_number=forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter mobile number'}),
										max_length=10,required=True)

	class Meta:
		model=profile
		fields=['dob','profile_pic','mobile_number']
